services:
  rocketlaunch_feishu:
    env_file:
      - .env.prod
    image: rocketlaunch_feishu:latest
    container_name: rocketlaunch_feishu
    network_mode: "host"
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    init: true